script:
  - bundle exec rake db:migrate spec RAILS_ENV=test
env:
  - GEM=core
  - GEM=pages
  - GEM=attachments
before_install:
  - gem update --system
  - gem --version
  - gem install bundler
  - cd $GEM
rvm:
  - 1.9.3
  - 2.0.0
